# HW2: Encrypt and Decrypt
#
# In this exercise, we will write functions to encrypt and decrypt strings that only consist of lower-case characters.
#
# 1. Use `seq_along` function to map the characters to their positions i.e. a -> 1, b -> 2, ..., z -> 26.
#    Store the result into tibble `t1` with 2 columns: character and position. Each row contains a character and its position.
#    Hint: You may use `letters` to obtain a vector of 26 characters.
# 2. Use tibble `t1` to assign to `n1` the position of character `"n"`. Note: `n1` should be an integer instead of a list.
# 3. Write a function `move(char,nstep=5)` that return the character that is `nstep` steps after the input character `char`.
#    Note: When the position is larger than 26, start from the beginning i.e. 1.
#    Example : both `move("a",nstep=1)` and `move("z",nstep=2)` should return character `"b"`.
# 4. Use `strsplit` function to split the string "statistics" into characters and then apply the `move` function to move each element in the string by 5 steps using `sapply`. The result should be stored into a vector `v1`.
# 5. Write a function `encrypt(str,nstep)`. This function returns a string that each element is moved _nstep_ steps by using `move` function.
# 6. Write a function `decrypt(str,nstep)` to decrypt the string generated by `encrypt` function.

## Do not modify this line! ## Write your code for 1. after this line! ##

library(tibble)
t1<- tibble(character=letters, position=seq_along(letters))       
       
## Do not modify this line! ## Write your code for 2. after this line! ##

n1 <- t1$position[t1$character == 'n']

## Do not modify this line! ## Write your code for 3. after this line! ##

## Do not modify this line! ## Write your code for 4. after this line! ##

## Do not modify this line! ## Write your code for 5. after this line! ##

## Do not modify this line! ## Write your code for 6. after this line! ##